# Generated by Django 4.1.9 on 2023-06-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Score', models.CharField(max_length=10)),
                ('Genres', models.CharField(max_length=255)),
                ('English_name', models.CharField(max_length=255)),
                ('Japanese_name', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=50)),
                ('Episodes', models.CharField(max_length=50)),
                ('Aired', models.CharField(max_length=100)),
                ('Premiered', models.CharField(max_length=50)),
                ('Producers', models.CharField(max_length=255)),
                ('Licensors', models.CharField(max_length=255)),
                ('Studios', models.CharField(max_length=255)),
                ('Source', models.CharField(max_length=50)),
                ('Duration', models.CharField(max_length=50)),
                ('Rating', models.CharField(max_length=100)),
                ('Ranked', models.CharField(max_length=10)),
                ('Popularity', models.IntegerField()),
            ],
        ),
    ]
